### ISSUE TITLE
Website of repository is incorrect URL

### ISSUE THREAD

**Issue by jmkeol** [McbeEringi/esbe-2g#14]
![image](https://user-images.githubusercontent.com/63786778/79529517-392be980-80b0-11ea-84ac-137a67975f19.png)
[https://mcbeeringi.github.com/esbe-2g](https://mcbeeringi.github.com/esbe-2g) does not go anywhere.
It should be [https://mcbeeringi.github**.io**/esbe-2g](https://mcbeeringi.github.io/esbe-2g)

**Comment by McbeEringi** [comment]
thank you for reporting!
