### ISSUE TITLE
ESBG_2G v5.0 Crashs bedrock Windows 10

### ISSUE THREAD

**Issue by Frankeinst** [McbeEringi/esbe-2g#21]
When I try to start a world or enter a server (using the last version of MC 1.16.1 Bedrock version Windows 10) the game crash and don't show me nothing (like report or something like that).

**Comment by jmkeol** [comment]
Are you sure it's related to ESBE 2G? Try doing what you are doing without ESBE 2G.

**Comment by Frankeinst** [comment]
Without ESBE 2G the world or the server opens normally, I used another shaders (called Energy Shaders (I think)) and all the blocks turn to transparent.

**Comment by jmkeol** [comment]
I'd try deleting the ESBE 2G (Settings > Storage) and redownloading it.

ESBE 2G 5.0 works fine on my Windows 10 1.16.1.

**Comment by Frankeinst** [comment]
Where folder is that?

**Comment by jmkeol** [comment]
It's in Minecraft's in game settings.
![image](https://user-images.githubusercontent.com/63786778/87214055-04f15d80-c36d-11ea-816e-2fed7d7325c7.png)

**Comment by Igniiiis** [comment]
I have the exact same issue
My graphics card is a rx 580 8g
i think it has something to do with the latest amd radeon drivers, im going to try with older ones
pls Frankeinst, if u have solved the problem, can u say how u did, please

**Comment by Frankeinst** [comment]
> I have the exact same issue
> My graphics card is a rx 580 8g
> i think it has something to do with the latest amd radeon drivers, im going to try with older ones
> pls Frankeinst, if u have solved the problem, can u say how u did, please

I didnt solved that, and i have a laptop with gtx 950m, i did what jmkeol said but didnt changed nothing.

**Comment by Igniiiis** [comment]
> > I have the exact same issue
> > My graphics card is a rx 580 8g
> > i think it has something to do with the latest amd radeon drivers, im going to try with older ones
> > pls Frankeinst, if u have solved the problem, can u say how u did, please
> 
> I didnt solved that, and i have a laptop with gtx 950m, i did what jmkeol said but didnt changed nothing.

:(

I saw on youtube that creating the world in windowed mode can fix issues... im gonna try this later

**Comment by Igniiiis** [comment]
> > I have the exact same issue
> > My graphics card is a rx 580 8g
> > i think it has something to do with the latest amd radeon drivers, im going to try with older ones
> > pls Frankeinst, if u have solved the problem, can u say how u did, please
> 
> I didnt solved that, and i have a laptop with gtx 950m, i did what jmkeol said but didnt changed nothing.

I finally solved the issue!!!
Instead of putting the .mcpack in the resource_packs folder, just double click on it and it will start Minecraft. then it will say, importation started and importation finished.

**Comment by McbeEringi** [comment]
> Instead of putting the .mcpack in the resource_packs folder, just double click on it

Thank you for finding the solution!
