### ISSUE TITLE
Sky lag on Android and Windows 10

### ISSUE THREAD

**Issue by Loco1911** [McbeEringi/esbe-2g#25]
The sky causes lag both in my Redmi 7 with a Snapdragon 632 and 3gb of ram, and in my laptop with an i3 2348m and an Intel HD 3000 and 8gb of ram

**Comment by McbeEringi** [comment]
![4A61EB00-DE5B-452E-9D2D-17095B71D9FC](https://user-images.githubusercontent.com/46889548/90005927-f0d5ae80-dcd2-11ea-8a53-c8b71bd891b2.png)

shader>glsl>sky.fsh
and
shader>hlsl>sky.fsh.hlsl

change
`		float cm = fBM(uw?4:6,lb,.8,pos*3.-TOTAL_REAL_WORLD_TIME*.002);
		if(cm>0.){
			〜
		}
`
to
`		float cm = fBM(4,lb,.8,pos*3.-TOTAL_REAL_WORLD_TIME*.002);
		/*if(cm>0.){
			〜
		}*/
`
This will be disable clouds' shadow and Reduce the frequency of noise generation
I hope it helps you.

**Comment by Loco1911** [comment]
Thank you for the help!
