### ISSUE TITLE
(Suggestion) Add settings to the Shader

### ISSUE THREAD

**Issue by Loco1911** [McbeEringi/esbe-2g#26]
It would be good if it had options such as the ESTN Shader, for example using the default sky, changing the brightness and color of the shader, etc.

**Comment by McbeEringi** [comment]
There was a setting file in legacy ESBE.
But I realized it cause a lot of lags.
So I removed it in ESBE_2G.
All you have to do is edit the code directly.
If you have any questions, please ask me.
Sorry for the inconvenience.

**Comment by Loco1911** [comment]
Thanks for the explanation, hopefully one day it can be implemented
